### ISSUE TITLE
Agent image problem, with this configuration in compose. 

### ISSUE THREAD

**Issue by LinuxCuba** [heyValdemar/zabbix-traefik-letsencrypt-docker-compose#2]
This parameter in environments variable is no allowed, and crash container agent. ZBX_SERVER_HOST: 0.0.0.0/0

Without this, agent not allow connections from external zabbix server.

Unable to connect to [zabbix-server]:10051 [cannot connect to [[zabbix-server]:10051]: [111] Connection refused]

Thanks

**Comment by heyvaldemar** [comment]
hey, everything works fine for me. Make sure that you use the latest version of [Docker Engine and Docker Compose](https://www.heyvaldemar.com/install-docker-engine-and-docker-compose-on-ubuntu-server/).

You can also reach me and other IT guys on [Discord](https://discord.gg/AJQGCCBcqf).
